server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/subida?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: zhao
    password: z0130z
    driver-class-name: com.mysql.cj.jdbc.Driver