server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/subida?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: zhao
    password: z0130z
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
#    spring关闭启动标志
    banner-mode: off
mybatis-plus:
  global-config:
    db-config:
#      实体类映射表头
      table-prefix: tbl_
#      隐藏启动log
    banner: false

